apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - name: todos-api
          image: uniqueacr2023.azurecr.io/todos-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: TODO_API_PORT
              value: "8082"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-api-secrets
                  key: JWT_SECRET
            # ...
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          # Startup probe para permitir un arranque más largo
          startupProbe:
            httpGet:
              path: /health/ready
              port: 8082
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
