apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: microservices # Correcto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: acrformymicroservices-test.azurecr.io/users-api:github.sha
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: users-api-secrets
                  key: JWT_SECRET
            - name: SERVER_PORT
              value: "8083"
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: microservices
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
