apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  labels:
    app: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-message-processor
          image: acrformymicroservices20250424.azurecr.io/log-message-processor:github.sha
          env:
            - name: REDIS_HOST
              value: "redis-master.microservices.svc.cluster.local"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
