name: Terraform-Infr

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - infra/dev
      - feature/infra
      - infra/feature/automation
 

jobs:
  apply-infra:
    name: Apply infraestructure
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener código
      - name: Checkout repository
        uses: actions/checkout@v3                   # Clona tu repo para acceder a los .tf :contentReference[oaicite:0]{index=0}

      # 2. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3          # Instala la versión especificada de Terraform :contentReference[oaicite:1]{index=1}
        with:
          terraform_version: 1.11.3

      # 3. Autenticar en Azure
      - name: Login to Azure
        uses: azure/login@v1                        # Login con SPN usando el secreto AZURE_CREDENTIALS :contentReference[oaicite:2]{index=2}
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Terraform Init
        run: terraform init
        working-directory: terraform
  
      - name: Syntax validation
        run: terraform validate
        working-directory: terraform
  
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
  
      - name: Terraform Apply (automatic mode)
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Syntax validation
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply (automatic mode)
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
        working-directory: terraform